### ISSUE TITLE
Consider systematic download URLs

### ISSUE THREAD

**Issue by hohwille** [adoptium/jdk#4]
Thanks for making adoptium (and former AdoptOpenJDK). This is really a great initiative for the OSS world.
However, it would be lovely if you would consider to create your download URLs more systematic:
https://github.com/devonfw/ide/issues/641#issuecomment-991254071

Feel free to close as wont fix if you do not care but I would be very pleased if you at least notice and care somehow.
However, please never ever change URLs of already released artifacts.
The world would be so great if all software would be released like maven artefacts ;)

**Comment by karianna** [comment]
I've commented on that issue, clients should use our API, not downloading directly from GH.
